### ISSUE TITLE
Problem with @aragon/connect-core library

### ISSUE THREAD

**Issue by PJColombo** [CommonsSwarm/hatch-connector#13]
When we create the connector and we pass it a custom provider, Aragon Connect ends up using the default one when it makes calls to contracts on Ethereum (see [here](https://github.com/aragon/connect/blob/4475d1551d46bee617b048876242cfa049f6617d/packages/connect/src/connect.ts#L29)). This can be a problem when we need to change the xDAI endpoint due to overload/overuse issues on the node.

**Comment by GriffGreen** [comment]
Keeping this in favor of https://github.com/CommonsBuild/tec-hatch/issues/63

**Comment by GriffGreen** [comment]
PR Coming :-D

**Comment by GriffGreen** [comment]
@0xGabi tell us when you have the connect library updated!! :-D

**Comment by GriffGreen** [comment]
Working with Gabi before... making major progress this week!

**Comment by 0xGabi** [comment]
This should be fixed with: https://github.com/1Hive/connect/pull/12

We are going to release a new connect version and test it
